import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer/Footer'
import HeroSection from './components/Hero/Hero'
import StatsSection from './components/Stat/Stat'
import TrendingAppsSection from './components/TrendingApps/TrendingApps'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Home | Hero-IO-App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/logo-16.png',
        sizes: '16x16',
        type: 'image/png',
      },
      {
        url: '/logo-32.png',
        sizes: '32x32',
        type: 'image/png',
      },
    ],
    shortcut: '/logo-32.png',
    apple: '/logo-180.png',
  },
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Navbar />
        <HeroSection></HeroSection>
        <StatsSection></StatsSection>
        <TrendingAppsSection></TrendingAppsSection>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}